functional_prototype/ImoAnalytics/ImoAnalytics/Models/TipoImovel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ImoAnalytics.Models
{
    public class TipoImovel
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "O tipo do imóvel precisa ser inserido")]
        [MaxLength(50)]
        public String Tipo { get; set; }
    }
}

functional_prototype/ImoAnalytics/ImoAnalytics/Controllers/TipoImovelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ImoAnalytics.Models;

namespace ImoAnalytics.Controllers
{
    public class TipoImovelController : Controller
    {
        private ImoAnalyticsContext db = new ImoAnalyticsContext();

        // GET: TipoImovel
        public ActionResult Index()
        {
            return View(db.TipoImovel.ToList());
        }

        // GET: TipoImovel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovel.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // GET: TipoImovel/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoImovel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Tipo")] TipoImovel tipoImovel)
        {
            if (ModelState.IsValid)
            {
                db.TipoImovel.Add(tipoImovel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoImovel);
        }

        // GET: TipoImovel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovel.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // POST: TipoImovel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Tipo")] TipoImovel tipoImovel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoImovel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoImovel);
        }

        // GET: TipoImovel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovel.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // POST: TipoImovel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoImovel tipoImovel = db.TipoImovel.Find(id);
            db.TipoImovel.Remove(tipoImovel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/TipoImovel/Create.cshtml
@model ImoAnalytics.Models.TipoImovel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Cadastrar Tipo de imóvel</h3>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
            </div>
            <div class="row buttons-row">
                <div class="col-md-6 center">
                    <input type="submit" value="Cadastrar" class="principal-button" />
                </div>
                <div class="col-md-6 center">
                    <div class="principal-button-div">@Html.ActionLink("Limpar", "Create")</div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/TipoImovel/Delete.cshtml
@model ImoAnalytics.Models.TipoImovel

@{
    ViewBag.Title = "Delete";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h3 class="panel-title">Tem certeza que quer deletar esse tipo do imóvel?</h3>
            </div>
            <div class="col-md-4 icons-edit-remove">
                <a href="@Url.Action("Edit", "TipoImovel", new { id = Model.ID })" title="Editar venda"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "TipoImovel", new { id = Model.ID })" title="Remover venda"><i class="fa fa-trash"></i></a>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Tipo)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Tipo)</p>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Deletar" class="principal-button" /> <br /><br />
        <a href="@Url.Action("Details", "TipoImovel", new { id = Model.ID })" title="Voltar para os detalhes" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>
    </div>
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/TipoImovel/Details.cshtml
@model ImoAnalytics.Models.TipoImovel

@{
    ViewBag.Title = "Details";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h3 class="panel-title">Detalhes do tipo do imóvel</h3>
            </div>
            <div class="col-md-4 icons-edit-remove">
                <a href="@Url.Action("Edit", "TipoImovel", new { id = Model.ID })" title="Editar tipo de imóvel"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "TipoImovel", new { id = Model.ID })" title="Remover tipo de imóvel"><i class="fa fa-trash"></i></a>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Tipo)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Tipo)</p>
            </div>
        </div>
    </div>
</div>

<a href="@Url.Action("Index", "TipoImovel")" title="Voltar para a listagem" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>

functional_prototype/ImoAnalytics/ImoAnalytics/Views/TipoImovel/Edit.cshtml
@model ImoAnalytics.Models.TipoImovel

@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Editar tipo de imóvel</h3>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
            </div>
            <div class="row buttons-row">
                <div class="col-md-12 center">
                    <input type="submit" value="Cadastrar" class="principal-button" />
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/TipoImovel/Index.cshtml
@model IEnumerable<ImoAnalytics.Models.TipoImovel>

@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Vendas</h3>
    </div>
    <div class="header-row row">
        <div class="col-md-11">
            <p>@Html.DisplayNameFor(model => model.Tipo)</p>
        </div>
    </div>
    @foreach (var item in Model)
    {
        <div class="primary-color-row row">
            <div class="col-md-11">
                <p>@Html.DisplayFor(modelItem => item.Tipo)</p>
            </div>
            <div class="col-md-1">
                <a class="link-more" href="@Url.Action("Details", "TipoImovel", new { id = item.ID })" title="Mais informações"><i class="fa fa-ellipsis-h"></i></a>
            </div>
        </div>
    }
</div>