system/ImoAnalyticsSystem/ImoAnalyticsSystem/Models/Corretor.cs
using ImoAnalyticsSystem.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

namespace ImoAnalyticsSystem.Models
{
    public class Corretor : IdentityUser
    {
        // Propriedades do corretor
        [Display(Name = "Nome do corretor")]
        public String NomeCompleto { get; set; }

        [Display(Name = "CPF")]
        public String Cpf { get; set; }

        [Display(Name = "RG")]
        public String Rg { get; set; }

        [Display(Name = "Data de nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

        [Display(Name = "CEP")]
        public String Cep { get; set; }

        [Display(Name = "Endereço")]
        public String Endereco { get; set; }

        [Display(Name = "Número")]
        public int Numero { get; set; }

        [Display(Name = "Bairro")]
        public String Bairro { get; set; }

        [Display(Name = "Cidade")]
        public String Cidade { get; set; }

        [Display(Name = "Estado")]
        public String Estado { get; set; }

        [Display(Name = "Creci")]
        public int Creci { get; set; }

        [Display(Name = "Ativo")]
        public bool Ativo { get; set; }

        //Métodos auto gerados pelo módulo Identity do Entity Framework
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<Corretor> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }
    
}

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Controllers/CorretorController.cs
using ImoAnalyticsSystem.Business;
using ImoAnalyticsSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ImoAnalyticsSystem.ViewModels.IdentityViewModels;
using Microsoft.AspNet.Identity;

namespace ImoAnalyticsSystem.Controllers
{
    public class CorretorController : Controller
    {
        CorretorBusiness corretorBusiness = new CorretorBusiness();
        
        // GET: Corretor
        [Authorize]
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            List<Corretor> corretores;

            if (!String.IsNullOrEmpty(searchString))
            {
                corretores = corretorBusiness.SearchCorretoresByNome(searchString);
                if (corretores.Count() == 0)
                    ViewBag.noResults = true;
            }
            else
                corretores = corretorBusiness.GetCorretores();

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(corretores.OrderBy(c => c.NomeCompleto).ToPagedList(pageNumber, pageSize));
        }
    }
}

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Views/Corretor/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ImoAnalyticsSystem.Models.Corretor>

@{
    ViewBag.Title = "Corretores";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewBag.Title</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="panel-body search-list">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="group">
                        <p>Pesquisar corretor por nome</p>
                        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @type = "text", @class = "effect-1" })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="group">
                        <input type="submit" value="Pesquisar" />
                    </div>
                </div>
            </div>
        </div>
    }
    @if (Model.Count() > 0)
    {
        <div class="header-row row">
            <div class="col-md-4">
                <p>Nome</p>
            </div>
            <div class="col-md-3">
                <p>Telefone</p>
            </div>
            <div class="col-md-4">
                <p>E-mail</p>
            </div>
        </div>
        foreach (var item in Model)
        {
            <div class="primary-color-row row">
                <div class="col-md-4">
                    <p>@Html.DisplayFor(modelItem => item.NomeCompleto)</p>
                </div>
                <div class="col-md-3">
                    <p>@Html.DisplayFor(modelItem => item.PhoneNumber)</p>
                </div>
                <div class="col-md-4">
                    <p>@Html.DisplayFor(modelItem => item.Email)</p>
                </div>
                <div class="col-md-1">
                   @* <a class="link-more" href="@Url.Action("Details", "Corretor", new { id = item.ID })" title="Mais informações"><i class="fa fa-ellipsis-h"></i></a>*@
                </div>
            </div>
        }
    }
    else
    {
        if (ViewBag.noResults == true)
        {
            <div class="primary-color-row row">
                <center><p>Não existem resultados para a busca</p></center>
            </div>
        }
        else
        {
            <div class="primary-color-row row">
                <center><p>Não existem @ViewBag.title.ToLower() cadastrados</p></center>
            </div>
        }
    }
</div>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))