system/ImoAnalyticsSystem/ImoAnalyticsSystem/Models/Proprietario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ImoAnalyticsSystem.Models
{
    public class Proprietario
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "O nome do proprietário é obrigatório")]
        [MaxLength(250, ErrorMessage = "O tamanho máximo do nome é de 250 caracteres.")]
        [Display(Name = "Nome do proprietário")]
        public String NomeCompleto { get; set; }

        [Required(ErrorMessage = "O CPF é obrigatório.")]
        [MaxLength(14, ErrorMessage = "O tamanho máximo do CPF é de 14 caracteres.")]
        [Display(Name = "CPF")]
        public String Cpf { get; set; }

        [Required(ErrorMessage = "O RG é obrigatório.")]
        [Display(Name = "RG")]
        public String Rg { get; set; }

        [Required(ErrorMessage = "A data de nascimento é obrigatória.")]
        [Display(Name = "Data de nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

        [Required(ErrorMessage = "O telefone é obrigatório.")]
        [Phone]
        [Display(Name = "Número do celular")]
        public String Telefone { get; set; }

        [Required(ErrorMessage = "O CEP é obrigatório.")]
        [Display(Name = "CEP")]
        public String Cep { get; set; }

        [Required(ErrorMessage = "O endereço é obrigatório.")]
        [Display(Name = "Endereço")]
        public String Endereco { get; set; }

        [Required(ErrorMessage = "O número é obrigatório.")]
        [Display(Name = "Número")]
        public int Numero { get; set; }

        [Required(ErrorMessage = "O bairro é obrigatório.")]
        [Display(Name = "Bairro")]
        public String Bairro { get; set; }

        [Required(ErrorMessage = "A cidade é obrigatória.")]
        [Display(Name = "Cidade")]
        public String Cidade { get; set; }

        [Required(ErrorMessage = "O estado é obrigatório.")]
        [Display(Name = "Estado")]
        public String Estado { get; set; }

        [Required(ErrorMessage = "A conta bancária é obrigatóra.")]
        [Display(Name = "Conta bancária")]
        public String ContaBancaria { get; set; }

        [Required(ErrorMessage = "A agência é obrigatória.")]
        [Display(Name = "Agência")]
        public String Agencia { get; set; }

        [Required(ErrorMessage = "O banco é obrigatório.")]
        [Display(Name = "Banco")]
        public String Banco { get; set; }

        [ForeignKey("ProprietarioId")]
        public virtual ICollection<Imovel> Imoveis { get; set; }

        [Required]
        public Boolean Ativo { get; set; }

        [Required(ErrorMessage = "O e-mail é obrigatório.")]
        [EmailAddress]
        [Display(Name = "E-mail")]
        public String Email { get; set; }
    }
}

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Controllers/ProprietarioController.cs
using ImoAnalyticsSystem.Business;
using ImoAnalyticsSystem.Data;
using ImoAnalyticsSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ImoAnalyticsSystem.Controllers
{
    public class ProprietarioController : Controller
    {
        private ProprietarioBusiness proprietarioBusiness = new ProprietarioBusiness();

        // GET: Proprietario
        [Authorize]
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            List<Proprietario> proprietarios;

            if (!String.IsNullOrEmpty(searchString))
            {
                proprietarios = proprietarioBusiness.SearchProprietariosByNome(searchString);
                if(proprietarios.Count() == 0)
                    ViewBag.noResults = true;
            }
            else
                proprietarios = proprietarioBusiness.GetProprietarios();

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(proprietarios.OrderBy(p => p.NomeCompleto).ToPagedList(pageNumber, pageSize));
        }

        // GET: Proprietario/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietario proprietario = proprietarioBusiness.FindById(id);
            if (proprietario == null)
            {
                return HttpNotFound();
            }
            return View(proprietario);
        }

        // GET: Proprietario/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proprietario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,NomeCompleto,Cpf,Rg,DataNascimento,Telefone,Cep,Endereco,Numero,Bairro,Cidade,Estado,ContaBancaria,Agencia,Banco,Ativo,Email")] Proprietario proprietario)
        {
            string create = "";
            if (ModelState.IsValid)
            {
                create = proprietarioBusiness.Create(proprietario);
                if (create.Equals("OK"))
                    return RedirectToAction("Index");
            }

            if(!create.Equals(""))
                ModelState.AddModelError("Erro ao criar o proprietário: ", create);
            return View(proprietario);
        }

        // GET: Proprietario/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietario proprietario = proprietarioBusiness.FindById(id);
            if (proprietario == null)
            {
                return HttpNotFound();
            }
            return View(proprietario);
        }

        // POST: Proprietario/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ID,NomeCompleto,Cpf,Rg,DataNascimento,Telefone,Cep,Endereco,Numero,Bairro,Cidade,Estado,ContaBancaria,Agencia,Banco,Ativo,Email")] Proprietario proprietario)
        {
            string edit = "";
            if (ModelState.IsValid)
            {
                edit = proprietarioBusiness.Edit(proprietario);
                if (edit.Equals("OK"))
                    return RedirectToAction("Index");
            }

            if (!edit.Equals(""))
                ModelState.AddModelError("Erro ao editar o proprietário: ", edit);
            return View(proprietario);
        }

        // GET: Proprietario/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietario proprietario = proprietarioBusiness.FindById(id);
            if (proprietario == null)
            {
                return HttpNotFound();
            }
            return View(proprietario);
        }

        // POST: Proprietario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Proprietario proprietario = proprietarioBusiness.FindById(id);
            proprietarioBusiness.Delete(proprietario);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                proprietarioBusiness.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Views/Proprietario/Create.cshtml
@model ImoAnalyticsSystem.Models.Proprietario

@{
    ViewBag.Title = "Cadastrar proprietário";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">@ViewBag.Title</h3>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.NomeCompleto)</p>
                        @Html.EditorFor(model => model.NomeCompleto, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.NomeCompleto).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Cpf)</p>
                        @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Cpf).ToHtmlString()), @class = "effect-1 js-cpf" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Rg)</p>
                        @Html.EditorFor(model => model.Rg, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Rg).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.DataNascimento)</p>
                        @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.DataNascimento).ToHtmlString()), @class = "effect-1 js-data", @maxlength = 10 } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Telefone)</p>
                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Telefone).ToHtmlString()), @class = "effect-1 js-telefone" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Cep)</p>
                        @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Cep).ToHtmlString()), @class = "effect-1 js-cep" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Endereco)</p>
                        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Endereco).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Numero)</p>
                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @type = "number", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Numero).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Bairro)</p>
                        @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Bairro).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Cidade)</p>
                        @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Cidade).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Estado)</p>
                        @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Estado).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.ContaBancaria)</p>
                        @Html.EditorFor(model => model.ContaBancaria, new { htmlAttributes = new { @type = "number", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.ContaBancaria).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Agencia)</p>
                        @Html.EditorFor(model => model.Agencia, new { htmlAttributes = new { @type = "number", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Agencia).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Banco)</p>
                        @Html.EditorFor(model => model.Banco, new { htmlAttributes = new { @type = "text", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Banco).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="group">
                        <p>@Html.LabelFor(m => m.Email)</p>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @type = "email", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(m => m.Email).ToHtmlString()), @class = "effect-1" } })
                        <span class="focus-border"></span>
                    </div>
                </div>
            </div>
            <div class="row buttons-row">
                <div class="col-md-6 center">
                    <input type="submit" value="Cadastrar" class="principal-button" />
                </div>
                <div class="col-md-6 center">
                    <div class="principal-button-div">@Html.ActionLink("Limpar", "Create")</div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Views/Proprietario/Delete.cshtml
@model ImoAnalyticsSystem.Models.Proprietario

@{
    ViewBag.Title = "tem certeza que deseja deletar o/a proprietário(a) " + Model.NomeCompleto + "?";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">@ViewBag.Title</h3>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.NomeCompleto): </b> @Html.DisplayFor(model => model.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cpf): </b> @Html.DisplayFor(model => model.Cpf)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Rg): </b> @Html.DisplayFor(model => model.Rg)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.DataNascimento): </b> @Html.DisplayFor(model => model.DataNascimento)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Telefone): </b> @Html.DisplayFor(model => model.Telefone)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cep): </b> @Html.DisplayFor(model => model.Cep)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Endereco): </b> @Html.DisplayFor(model => model.Endereco)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Numero): </b> @Html.DisplayFor(model => model.Numero)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Bairro): </b> @Html.DisplayFor(model => model.Bairro)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cidade): </b> @Html.DisplayFor(model => model.Cidade)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Estado): </b> @Html.DisplayFor(model => model.Estado)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.ContaBancaria): </b> @Html.DisplayFor(model => model.ContaBancaria)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Agencia): </b> @Html.DisplayFor(model => model.Agencia)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Banco): </b> @Html.DisplayFor(model => model.Banco)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Ativo): </b> @Html.DisplayFor(model => model.Ativo)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Email): </b> @Html.DisplayFor(model => model.Email)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>Quantidade de imóveis: </b> @Html.DisplayFor(model => model.Imoveis.Count)</p>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Deletar" class="principal-button" /> <br /><br />
        <a href="@Url.Action("Details", "Proprietario", new { id = Model.ID })" title="Voltar para os detalhes" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>
    </div>
}

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Views/Proprietario/Details.cshtml
@model ImoAnalyticsSystem.Models.Proprietario

@{
    ViewBag.Title = "Detalhes do proprietário " + Model.NomeCompleto;
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h3 class="panel-title">@ViewBag.Title</h3>
            </div>
            <div class="col-md-4 icons-edit-remove">
                <a href="@Url.Action("Edit", "Proprietario", new { id = Model.ID })" title="Editar proprietário"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "Proprietario", new { id = Model.ID })" title="Remover proprietário"><i class="fa fa-trash"></i></a>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.NomeCompleto): </b> @Html.DisplayFor(model => model.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cpf): </b> @Html.DisplayFor(model => model.Cpf)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Rg): </b> @Html.DisplayFor(model => model.Rg)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.DataNascimento): </b> @Html.DisplayFor(model => model.DataNascimento)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Telefone): </b> @Html.DisplayFor(model => model.Telefone)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cep): </b> @Html.DisplayFor(model => model.Cep)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Endereco): </b> @Html.DisplayFor(model => model.Endereco)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Numero): </b> @Html.DisplayFor(model => model.Numero)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Bairro): </b> @Html.DisplayFor(model => model.Bairro)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Cidade): </b> @Html.DisplayFor(model => model.Cidade)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Estado): </b> @Html.DisplayFor(model => model.Estado)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.ContaBancaria): </b> @Html.DisplayFor(model => model.ContaBancaria)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Agencia): </b> @Html.DisplayFor(model => model.Agencia)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Banco): </b> @Html.DisplayFor(model => model.Banco)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Ativo): </b> @Html.DisplayFor(model => model.Ativo)</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>@Html.DisplayNameFor(model => model.Email): </b> @Html.DisplayFor(model => model.Email)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-md-6">
            <div class="col-md-12">
                <p><b>Quantidade de imóveis: </b> @Html.DisplayFor(model => model.Imoveis.Count)</p>
            </div>
        </div>
    </div>
</div>

<a href="@Url.Action("Index", "TipoImovel")" title="Voltar para a listagem" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>

system/ImoAnalyticsSystem/ImoAnalyticsSystem/Views/Proprietario/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ImoAnalyticsSystem.Models.Proprietario>

@{
    ViewBag.Title = "Proprietários";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewBag.Title</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="panel-body search-list">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="group">
                        <p>Pesquisar proprietário por nome</p>
                        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @type = "text", @class = "effect-1" })
                        <span class="focus-border"></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="group">
                        <input type="submit" value="Pesquisar" />
                    </div>
                </div>
            </div>
        </div>
    }
    @if (Model.Count() > 0)
    {
        <div class="header-row row">
            <div class="col-md-4">
                <p>Nome</p>
            </div>
            <div class="col-md-3">
                <p>Telefone</p>
            </div>
            <div class="col-md-4">
                <p>E-mail</p>
            </div>
        </div>
        foreach (var item in Model)
        {
            <div class="primary-color-row row">
                <div class="col-md-4">
                    <p>@Html.DisplayFor(modelItem => item.NomeCompleto)</p>
                </div>
                <div class="col-md-3">
                    <p>@Html.DisplayFor(modelItem => item.Telefone)</p>
                </div>
                <div class="col-md-4">
                    <p>@Html.DisplayFor(modelItem => item.Email)</p>
                </div>
                <div class="col-md-1">
                    <a class="link-more" href="@Url.Action("Details", "Proprietario", new { id = item.ID })" title="Mais informações"><i class="fa fa-ellipsis-h"></i></a>
                </div>
            </div>
        }
    }
    else
    {
        if (ViewBag.noResults == true)
        {
            <div class="primary-color-row row">
                <center><p>Não existem resultados para a busca</p></center>
            </div>
        }
        else
        {
            <div class="primary-color-row row">
                <center><p>Não existem @ViewBag.title.ToLower() cadastrados</p></center>
            </div>
        }
    }
</div>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))