functional_prototype/ImoAnalytics/ImoAnalytics/Models/Venda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ImoAnalytics.Models
{
    public class Venda
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "Data da venda")]
        [Required(ErrorMessage = "A data da venda é obrigatória")]
        public DateTime DataVenda { get; set; }

        [Display(Name = "Imóvel")]
        [Required(ErrorMessage = "O imóvel vendido é obrigatório.")]
        public int ImovelId { get; set; }

        [Display(Name = "Corretor")]
        [Required(ErrorMessage = "O corretor que vendeu o imóvel é obrigatório.")]
        public int CorretorId { get; set; }

        [Display(Name = "Interessado")]
        [Required(ErrorMessage = "O interessado que comprou o imóvel é obrigatório.")]
        public int InteressadoId { get; set; }

        [Display(Name = "Valor de venda")]
        [Required(ErrorMessage = "O valor da venda é obrigatória.")]
        public double ValorVenda { get; set; }

        [Display(Name = "Comissão da imobiliária")]
        public double ComissaoImobiliaria { get; set; }

        [Display(Name = "Comissão do corretor")]
        public double ComissaoCorretor { get; set; }

        public virtual Imovel Imovel { get; set; }

        public virtual Corretor Corretor { get; set; }
        
        public virtual Interessado Interessado { get; set; }
    }
}

functional_prototype/ImoAnalytics/ImoAnalytics/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ImoAnalytics.Models;

namespace ImoAnalytics.Controllers
{
    public class VendaController : Controller
    {
        private ImoAnalyticsContext db = new ImoAnalyticsContext();

        // GET: Venda
        public ActionResult Index()
        {
            var vendas = db.Venda.Include(v => v.Corretor).Include(v => v.Imovel).Include(v => v.Interessado);
            return View(vendas.ToList());
        }

        // GET: Venda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Venda.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            return View(venda);
        }

        // GET: Venda/Create
        public ActionResult Create()
        {
            ViewBag.CorretorId = new SelectList(db.Corretor, "ID", "NomeCompleto");
            ViewBag.ImovelId = new SelectList(db.Imovel, "ID", "ID");
            ViewBag.InteressadoId = new SelectList(db.Interessado, "ID", "NomeCompleto");
            return View();
        }

        // POST: Venda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,DataVenda,ImovelId,CorretorId,InteressadoId,ValorVenda,ComissaoImobiliaria,ComissaoCorretor")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                venda.ComissaoImobiliaria = venda.ValorVenda * 0.06;
                venda.ComissaoCorretor = venda.ComissaoImobiliaria * 0.2;
                db.Venda.Add(venda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CorretorId = new SelectList(db.Corretor, "ID", "NomeCompleto", venda.CorretorId);
            ViewBag.ImovelId = new SelectList(db.Imovel, "ID", "ID", venda.ImovelId);
            ViewBag.InteressadoId = new SelectList(db.Interessado, "ID", "NomeCompleto", venda.InteressadoId);
            return View(venda);
        }

        // GET: Venda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Venda.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            ViewBag.CorretorId = new SelectList(db.Corretor, "ID", "NomeCompleto", venda.CorretorId);
            ViewBag.ImovelId = new SelectList(db.Imovel, "ID", "ID", venda.ImovelId);
            ViewBag.InteressadoId = new SelectList(db.Interessado, "ID", "NomeCompleto", venda.InteressadoId);
            return View(venda);
        }

        // POST: Venda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,DataVenda,ImovelId,CorretorId,InteressadoId,ValorVenda,ComissaoImobiliaria,ComissaoCorretor")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                venda.ComissaoImobiliaria = venda.ValorVenda * 0.06;
                venda.ComissaoCorretor = venda.ComissaoImobiliaria * 0.2;
                db.Entry(venda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CorretorId = new SelectList(db.Corretor, "ID", "NomeCompleto", venda.CorretorId);
            ViewBag.ImovelId = new SelectList(db.Imovel, "ID", "ID", venda.ImovelId);
            ViewBag.InteressadoId = new SelectList(db.Interessado, "ID", "NomeCompleto", venda.InteressadoId);
            return View(venda);
        }

        // GET: Venda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Venda.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            return View(venda);
        }

        // POST: Venda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venda venda = db.Venda.Find(id);
            db.Venda.Remove(venda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/Venda/Create.cshtml
@model ImoAnalytics.Models.Venda

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Cadastrar Venda</h3>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6">
                    <div class="group">
                        @Html.EditorFor(model => model.DataVenda, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.DataVenda, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        <label style="display: flex; width: 100%; font-size: 14px; align-items: center;">Código do Imóvel</label>
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("ImovelId", null, htmlAttributes: new { @class = "   " })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        @Html.LabelFor(model => model.CorretorId, htmlAttributes: new { @class = "control-label col-md-2", @style = "display: flex; width: 100%; font-size: 14px; align-items: center;" })
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("CorretorId", null, htmlAttributes: new { @class = "" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        @Html.LabelFor(model => model.InteressadoId, htmlAttributes: new { @class = "control-label col-md-2", @style = "display: flex; width: 100%; font-size: 14px; align-items: center;" })
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("InteressadoId", null, htmlAttributes: new { @class = "" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="group">
                        @Html.EditorFor(model => model.ValorVenda, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.ValorVenda, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
            </div>
            <div class="row buttons-row">
                <div class="col-md-6 center">
                    <input type="submit" value="Cadastrar" class="principal-button" />
                </div>
                <div class="col-md-6 center">
                    <div class="principal-button-div">@Html.ActionLink("Limpar", "Create")</div>
                </div>
            </div>
        </div>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/Venda/Delete.cshtml
@model ImoAnalytics.Models.Venda

@{
    ViewBag.Title = "Delete";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Tem certeza que quer deletar a venda?</h3>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Corretor.NomeCompleto)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Corretor.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>Código do @Html.DisplayNameFor(model => model.Imovel)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Imovel.ID)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Interessado)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Interessado.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.DataVenda)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.DataVenda)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ValorVenda)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ValorVenda)</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ComissaoImobiliaria)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ComissaoImobiliaria)</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ComissaoCorretor)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ComissaoCorretor)</p>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Deletar" class="principal-button" /> <br /><br />
        <a href="@Url.Action("Details", "Venda", new { id = Model.ID })" title="Voltar para os detalhes da venda" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>
    </div>
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/Venda/Details.cshtml
@model ImoAnalytics.Models.Venda

@{
    ViewBag.Title = "Details";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h3 class="panel-title">Detalhes da venda</h3>
            </div>
            <div class="col-md-4 icons-edit-remove">
                <a href="@Url.Action("Edit", "Venda", new { id = Model.ID })" title="Editar venda"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "Venda", new { id = Model.ID })" title="Remover venda"><i class="fa fa-trash"></i></a>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Corretor.NomeCompleto)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Corretor.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>Código do @Html.DisplayNameFor(model => model.Imovel)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Imovel.ID)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.Interessado)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.Interessado.NomeCompleto)</p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.DataVenda)</b></p>
            </div>
            <div class="col-sm-6">
                <p>@Html.DisplayFor(model => model.DataVenda)</p>
            </div>
        </div>
    </div>
    <div class="primary-color-row row">
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ValorVenda)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ValorVenda)</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ComissaoImobiliaria)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ComissaoImobiliaria)</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-6">
                <p><b>@Html.DisplayNameFor(model => model.ComissaoCorretor)</b></p>
            </div>
            <div class="col-sm-6">
                <p>R$@Html.DisplayFor(model => model.ComissaoCorretor)</p>
            </div>
        </div>
    </div>
</div>

<a href="@Url.Action("Index", "Venda")" title="Voltar para a listagem" class="voltar-icon"><i class="fa fa-arrow-left"></i></a>

functional_prototype/ImoAnalytics/ImoAnalytics/Views/Venda/Edit.cshtml
@model ImoAnalytics.Models.Venda

@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Editar Venda</h3>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6">
                    <div class="group">
                        @Html.EditorFor(model => model.DataVenda, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.DataVenda, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        <label style="display: flex; width: 100%; font-size: 14px; align-items: center;">Código do Imóvel</label>
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("ImovelId", null, htmlAttributes: new { @class = "   " })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        @Html.LabelFor(model => model.CorretorId, htmlAttributes: new { @class = "control-label col-md-2", @style = "display: flex; width: 100%; font-size: 14px; align-items: center;" })
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("CorretorId", null, htmlAttributes: new { @class = "" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-sm-4" style="display: flex; height: 75px; align-items: center; justify-content: center;">
                        @Html.LabelFor(model => model.InteressadoId, htmlAttributes: new { @class = "control-label col-md-2", @style = "display: flex; width: 100%; font-size: 14px; align-items: center;" })
                    </div>
                    <div class="col-md-8">
                        @Html.DropDownList("InteressadoId", null, htmlAttributes: new { @class = "" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="group">
                        @Html.EditorFor(model => model.ValorVenda, new { htmlAttributes = new { @type = "text" } })
                        <span class="highlight"></span>
                        <span class="bar"></span>
                        @Html.LabelFor(model => model.ValorVenda, htmlAttributes: new { @class = "control-label" })
                    </div>
                </div>
            </div>
            <div class="row buttons-row">
                <div class="col-md-12 center">
                    <input type="submit" value="Salvar" class="principal-button" />
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

functional_prototype/ImoAnalytics/ImoAnalytics/Views/Venda/Index.cshtml
@model IEnumerable<ImoAnalytics.Models.Venda>

@{
    ViewBag.Title = "Index";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Vendas</h3>
    </div>
    <div class="header-row row">
        <div class="col-md-4">
            <p>Código do @Html.DisplayNameFor(model => model.Imovel)</p>
        </div>
        <div class="col-md-2">
            <p>@Html.DisplayNameFor(model => model.Imovel.Bairro)</p>
        </div>
        <div class="col-md-3">
            <p>@Html.DisplayNameFor(model => model.Interessado)</p>
        </div>
        <div class="col-md-2">
            <p>@Html.DisplayNameFor(model => model.ValorVenda)</p>
        </div>
    </div>
    @foreach (var item in Model)
    {
        <div class="primary-color-row row">
            <div class="col-md-4">
                <p>@Html.DisplayFor(modelItem => item.Imovel.ID)</p>
            </div>
            <div class="col-md-2">
                <p>@Html.DisplayFor(modelItem => item.Imovel.Bairro)</p>
            </div>
            <div class="col-md-3">
                <p>@Html.DisplayFor(modelItem => item.Interessado.NomeCompleto)</p>
            </div>
            <div class="col-md-2">
                <p>R$@Html.DisplayFor(modelItem => item.ValorVenda)</p>
            </div>
            <div class="col-md-1">
                <a class="link-more" href="@Url.Action("Details", "Venda", new { id = item.ID })" title="Mais informações"><i class="fa fa-ellipsis-h"></i></a>
            </div>
        </div>
    }
</div>
    